#docker-compose up --build
#docker compose down
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JmpGer123
      POSTGRES_DB: Database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=JmpGer123
      - DB_NAME=Database
      - DB_PORT=5432
      - PORT=5001
      - NODE_ENV=production
      # Variables pour la base de données de messagerie
      - CHAT_DB_HOST=db
      - CHAT_DB_USER=postgres
      - CHAT_DB_PASSWORD=JmpGer123
      - CHAT_DB_NAME=Database
      - CHAT_DB_PORT=5432
      # Variables pour le client
      - CLIENT_URL=http://localhost
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - VITE_API_URL=/api
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  pgdata: